# For help setting up Nano, go to https://github.com/doamatto/nano/wiki

# Setup site SEO: https://github.com/doamatto/nano/wiki/Configuring-SEO
lang: en-GB
title: "Nano for Jekyll"
description: "Nano is a lightweight Jekyll theme built to work great on all platforms, respect user privacy, and load at lightning-fast speeds."
author: "doamatto"
logo: "/assets/logo.svg"
favicon: "/assets/logo.svg"
url: "https://doamatto.xyz/nano"

classicnews: false # Bring back the pre-v0.3 newsroom look
unsafecontent: false # DO NOT CHANGE WITHOUT READING THIS: https://github.com/doamatto/nano/wiki/Content-Security-Policy

# Import fonts to use on your site: https://github.com/doamatto/nano/wiki/Importing-Fonts
font-import:
  - "https://cdn.doamatto.xyz/inter.min.css"
  - "https://cdn.doamatto.xyz/ibm.min.css"

# Setup site verifications: https://github.com/doamatto/nano/wiki/Site-Verifications
alexaverify: ""
bingverify: ""
dailyverify: ""
googleverify: ""
nortonverify: ""
specificverify: ""
pinverify: ""
plingverify: ""
wotverify: ""
yandexverify: ""

# Setup site analytics: https://github.com/doamatto/nano/wiki/Analytics
simpleanalytics: false 
fathomanalytics: false
fathomsite: ""
customfathomurl: ""
matomoanalytics: false
matomositeid: ""
matomourl: ""
plausibleanalytics: false
customplausibleurl: ""

# Setup header and footer: https://github.com/doamatto/nano/wiki/Configuring-Navigation-and-Footer-Links
tagline: "Nano for Jekyll"
navigation:
  - title: About
    url: /about-nano/
  - title: Docs
    url: "https://github.com/doamatto/nano/wiki"
footerLinks:
  - title: Imprint
    url: "https://doamatto.xyz/imprint"
  - title: Privacy Policy
    url: "https://doamatto.xyz/privacy"
  - title: Contact
    url: "https://doamatto.xyz/contact"
webSource: "https://github.com/doamatto/nano"
copyrightName: [ "doamatto" ]
copyrightYear: [ "2018-2020" ]

# Don't edit below this line without knowing what you're doing

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano-theme.gemspec
  - .jekyll-cache

feed:
  excerpt_only: false
  path: atom.xml

plugins:
  - jekyll
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty
