# For help setting up Nano, go to https://github.com/doamatto/nano/wiki

lang: en-GB # Site language
title: "Nano" # Site name; SEO
description: "Nano is a lightweight Jekyll theme built to work great on all platforms, respect user privacy, and load at lightning-fast speeds." # Site description; SEO
author: "doamatto" # For SEO
logo: "/assets/logo.svg" # Site logo
favicon: "/assets/logo.svg" # Add a favicon

font-import:
  - "https://cdn.doamatto.xyz/inter.min.css" # URL to font for importing
  - "https://cdn.doamatto.xyz/ibm.min.css" # URL to font for importing

alexaverify: "" # Alexa verification. Leave blank to exclude.
bingverify: "" # Bing Verification. Leave blank to exclude.
dailyverify: "" # DailyMotion Verification. Leave blank to exlcude.
googleverify: "" # Google verificiation. Leave blank to exclude.
nortonverify: "" # Norton verification. Leave blank to exclude.
specificverify: "" # SpecificFeeds verification. Leave blank to exclude.
pinverify: "" # Pinterest verification. Leave blank to exclude.
plingverify: "" # Pling/OpenDesktop verification. Leave blank to exclude.
wotverify: "" # World of Trust verification. Leave blank to exclude.
yandexverify: "" # Yandex verification. Leave blank to exclude.

simpleanalytics: false # Don't enable if you don't know what this does
fathomanalytics: false # Don't enable if you don't know what this does
fathomsite: "" # This is the site ID/name that you're supposed to use as the site attribute on the script
customfathomurl: "" # Make sure this is the direct url to the script for Fathom Analytics; do not include 'https://'
matomoanalytics: false # Don't enable if you don't know what this does
matomositeid: "" # Your site ID (you can find this in the Matomo dashboard)
matomourl: "" # Your Matomo instance (you can find this in the Matomo dashboard); do not include 'https://' or a trailing '/'

tagline: "Nano for Jekyll"
navigation: # Control the Navigation Bar
  - title: About
    url: /about-nano/
  - title: Docs
    url: "https://github.com/doamatto/nano/wiki"

webSource: "https://github.com/doamatto/nano" # Contribution Link
copyrightName: [ "doamatto" ] # Text for after copyright
copyrightYear: [ "2018-2020" ] # Overwrite the updating year counter
footerLinks: # Control the Footer Links
  - title: Imprint
    url: "https://doamatto.xyz/imprint"
  - title: Privacy Policy
    url: "https://doamatto.xyz/privacy"
  - title: Contact
    url: "https://doamatto.xyz/contact"

# Don't edit below this line

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano.gemspec
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty