lang: en-GB # Site language
title: "Nano" # Site name; SEO
description: "" # Site description; SEO
author: "doamatto" # For SEO
logo: "/assets/logo.svg" # Site logo
favicon: "/assets/logo.svg" # Add a favicon.

tagline: "Nano for Jekyll"
navigation: # Control the Navigation Bar
  - title: Home
    url: /
  - title: About Nano
    url: /about-nano/
  - title: About Dev
    url: /about/

webSource: "https://github.com/doamatto/nano" # Contribution Link
copyrightName: [ "doamatto" ] # Text for after copyright
copyrightYear: [ "2018-2020" ] # Overwrite the updating year counter
footerLinks: # Control the Footer Links
  - title: Imprint
    url: "https://doamatto.xyz/imprint"
  - title: Privacy Policy
    url: "https://doamatto.xyz/privacy"
  - title: Contact
    url: "https://doamatto.xyz/contact"

# Don't edit below this line

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano.gemspec
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass