exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano.gemspec
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter

author: # For SEO

sass:
  style: compressed
  sass_dir: _sass
permalink: pretty # /YYYY/MM/DD/page-name/
excerpt_separator: <!-- more -->

encoding: utf-8 # Change if you know you aren't using
lang: en-GB # Site language
title: "Nano" # Site name
description: "" # Site description

favicons: # Add a favicon. It isn't recommended to go over 64x64
  64: '/assets/favicon@64.png'

navigation: # Control the Navigation Bar
  - title: Home
    url: /
  - title: About Nano
    url: /about-nano/
  - title: About doamatto
    url: /about/

footerLinks: # Control the Footer Links
  - title: Imprint
    url: /imprint
  - title: Privacy Policy
    url: /privacy
  - title: Contact
    url: /contact