# For help setting up Nano, go to https://github.com/doamatto/nano/wiki

lang: en-GB # Site language
title: "Nano" # Site name; SEO
description: "Nano is a lightweight Jekyll theme built to work great on all platforms, respect user privacy, and load at lightning-fast speeds." # Site description; SEO
author: "doamatto" # For SEO
logo: "/assets/logo.svg" # Site logo
favicon: "/assets/logo.svg" # Add a favicon

# Import fonts to use on your site: https://github.com/doamatto/nano/wiki/Importing-Fonts
font-import:
  - "https://cdn.doamatto.xyz/inter.min.css"
  - "https://cdn.doamatto.xyz/ibm.min.css"

# Setup site verifications: https://github.com/doamatto/nano/wiki/Site-Verifications
alexaverify: ""
bingverify: ""
dailyverify: ""
googleverify: ""
nortonverify: ""
specificverify: ""
pinverify: ""
plingverify: ""
wotverify: ""
yandexverify: ""

# Setup site analytics: https://github.com/doamatto/nano/wiki/Analytics
simpleanalytics: false 
fathomanalytics: false
fathomsite: ""
customfathomurl: ""
matomoanalytics: false
matomositeid: ""
matomourl: ""
plausibleanalytics: true

tagline: "Nano for Jekyll"
navigation: # Control the Navigation Bar
  - title: About
    url: /about-nano/
  - title: Docs
    url: "https://github.com/doamatto/nano/wiki"

webSource: "https://github.com/doamatto/nano" # Contribution Link
copyrightName: [ "doamatto" ] # Text for after copyright
copyrightYear: [ "2018-2020" ] # Overwrite the updating year counter
footerLinks: # Control the Footer Links
  - title: Imprint
    url: "https://doamatto.xyz/imprint"
  - title: Privacy Policy
    url: "https://doamatto.xyz/privacy"
  - title: Contact
    url: "https://doamatto.xyz/contact"

# Don't edit below this line without knowing what you're doing

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - nano-theme.gemspec
  - .jekyll-cache

feed:
  excerpt_only: false
  path: atom.xml

plugins:
  - jekyll
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty