name: lint-and-debug
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.38.0
      with:
        bundler: Gemfile.lock
        bundler-cache: true
    
    - name: Setup Repo
      run: bundle install
    
    - name: Config/Versioning Debugging
      run: jekyll doctor
    
    - name: Test Build
      run: jekyll b
